# Generated by Django 4.0.4 on 2022-06-17 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customnewuser',
            name='email',
            field=models.CharField(max_length=20, unique=True, verbose_name='email_address'),
        ),
    ]
