# Generated by Django 4.0.4 on 2022-06-17 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customnewuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customnewuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='gmail_address'),
        ),
    ]
