# Generated by Django 4.2.2 on 2024-07-03 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0004_alter_customnewuser_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customnewuser',
            name='username',
            field=models.CharField(max_length=10, unique=True, verbose_name='username'),
        ),
    ]
