# Generated by Django 4.0.4 on 2022-06-20 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_blogs',
            name='code',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='my_blogs',
            name='text',
            field=models.TextField(unique=True),
        ),
        migrations.AlterField(
            model_name='my_blogs',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100, unique=True),
        ),
    ]
