# Generated by Django 4.0.4 on 2022-06-20 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0002_alter_my_blogs_code_alter_my_blogs_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='my_blogs',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
