# Generated by Django 6.0.2 on 2026-03-02 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myApp', '0003_alter_my_blogs_title'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='My_blogs',
            new_name='Blog',
        ),
    ]
